config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
   get "/" , {to: 'posts#index' , as: :root}
   resources :posts do 
   resources :comments, only: [:create, :destroy]
   end

   resources :users, only: [:new, :create]

   resource :sessions, only: [:new, :destroy, :create]
  
   get '/sign_up', to: "users#new"
   resources :users, only: [:create, :edit, :update, :destroy]

   get "/users/:id/change_password", { to: "users#password_edit", as: "edit_password" }
   patch "/users/:id/change_password", { to: "users#password_update", as: "update_password" }
end 

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    
if user.is_admin?
      can :manage,:all 
    end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    alias_action :create, :read, :update, :destroy, to: :crud

    can(:crud, User) do |user|
     user == user
    end
    can(:crud, Post)do |post|
    user==post.user
    end
    can(:crud, Comment) do |comment|
      user==comment.user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
    validates :body, presence: true 
end

app/models/post.rb
class Post < ApplicationRecord
    
    has_many :comments, dependent: :destroy
    belongs_to :user 
    
    validates :title, presence: true, uniqueness: true 
    validates :body, presence:true, length: {minimum:50}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :comments, dependent: :nullify
    has_many :posts, dependent: :nullify
    has_secure_password

    VALID_EMAIL_REGEX = /\A([\w+\-],?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX


    def full_name
        "#{first_name} #{last_name}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  private   
    def current_user
      if session[:user_id].present?
       @current_user ||= User.find_by_id session[:user_id]
      end
    end
    helper_method :current_user
    

    def user_signed_in?
      current_user.present?
    end
    helper_method :user_signed_in?
  
   
    def authenticate_user!
      unless user_signed_in?
       flash[:danger] = "Please sign in"
      redirect_to new_sessions_path
      end
    end
    helper_method :authenticate_user!
  
    
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
    def create
          @post = Post.find params[:post_id]
          @comment = Comment.new params.require(:comment).permit(:body)
          @comment.post = @post
          @comment.user=current_user 
        
          if @comment.save
              redirect_to post_path(@post)
          else
              flash[:notice] = "Failed to create comment"
              render 'posts/show'
            end
    end
      
      def destroy
        @comment = Comment.find params[:id]
         if can?(:crud, @comment)
            @comment.delete
            redirect_to post_path(@comment.post)
         else
            head :unauthorized
            redirect_to root_path, alert: 'Not Authorized'
         end
      end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    before_action :authorize!, only: [:edit, :update, :destroy]


    def index
        @posts = Post.all.order('created_at DESC')
    end

    def new
        @post = Post.new
    end
    
    def create
        @post = Post.new post_params
        @post.user = current_user 
        if @post.save
            flash[:notice] = "Post created successfully"
            redirect_to posts_path(@post) 
        else
            render :new 
        end
    end

    def show 
        @comment = Comment.new
        @comments = @post.comments
    end
    
    def edit
    end
    
    def update 
        if  @post.update post_params
        redirect_to post_path(@post)
       else
        render :edit
       end
    end

    def destroy
         @post.destroy
         redirect_to posts_path
    end 

    
    
    private
        def post_params
            params.require(:post).permit(:title, :body)
        end

        def find_post
             @post = Post.find(params[:id])
        end

        def authorize!
            redirect_to root_path, alert: 'Not Authorized' unless can?(:crud,@post)

        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   
     def new
    end

    def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id 
      redirect_to root_path, notice: "Logged in"
    else
      flash[:alert] = "Wrong email or password"
      render :new
    end
    end 

   def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, only: [:edit, :update]
    before_action :find_user, only: [:edit, :update]
    before_action :authorize, only: [:edit, :update] 
    before_action :authenticate_user!, only: [:edit, :update, :password_edit, :password_update]
    before_action :find_user, only: [:edit, :update, :password_edit, :password_update]
    before_action :authorize, only: [:edit, :update, :password_edit, :password_update] 
    def new
        @user = User.new
    end
    
      def create
        @user = User.new user_params
        if @user.save
          session[:user_id] = @user.id
          redirect_to root_path, notice: "Logged In!"
        else
          render :new
        end
    end
        
    def edit
    end


    def update
        if @user.update user_params
         flash[:success] = "Profile updated!"
            redirect_to root_path
         else
         flash[:danger] = @user.errors.full_messages.join(", ")
         redirect_to edit_user_path(@user)
        end
    end
        
    def password_edit
    end
    
    def password_update
        if @user&.authenticate(params[:user][:current_password])
            if @user.update user_params
            # if we use new_password and new_password_confirmation
            # password: params[:user][:new_password], 
            # password_confirmation: params[:user][:new_password_confirmation]
    
              flash[:success] = "Password updated!"
              redirect_to root_path
            else
              flash[:danger] = @user.errors.full_messages.join(", ")
              redirect_to edit_password_path(@user)
            end
        else
             flash[:danger] = "You've entered an invalid current password"
             redirect_to edit_password_path(@user)
        end
    
      
      end
    
    
    private
    
    def user_params
        params.require(:user).permit(
          :first_name,
          :last_name,
          :email,
          :password,
          :password_confirmation
        )
    end
    
    def find_user
        @user = User.find params[:id]
    end

    def authorize 
        unless can? :crud, @user
        flash[:danger] = "Not Authorized"
        redirect_to root_path
        end
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    
  </head>

  <body>
      
    
    <nav class="navbar navbar-expand-light bg-light">
    <%= link_to 'Blog On Rails', posts_path %>
    <div class="d-flex flex-row text-dark">
    <%= link_to 'Home', posts_path , class: 'btn btn-success nav-item'%>
    
    <%= link_to 'New Post', new_post_path , class: 'btn btn-success nav-item'%></li>
    
    <% if user_signed_in? %>
      <span class='text-muted mr-3'>Hello, 
          <%= link_to "#{current_user.full_name}", edit_user_path(current_user) %>
      </span>
        <%= link_to "Log Out", sessions_path, method: :delete, class: 'btn btn-danger' %>
      <% else %>
        
        <%= link_to "Log In", new_sessions_path, class: 'btn btn-success nav-item' %>
        
        <%= link_to "Sign Up", sign_up_path, class: 'btn btn-success nav-item' %>
      <% end %>
    </div>
 
   </nav>

   <div class='container'>

    <% flash.each do |type, message| %>
      <div class= "bg-<%= type %> p-3 rounded mb-2 shadow-sm">
        <%= message %>  
      </div>
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.present? %>
  <p>
    <%= @post.errors.full_messages.join(', ')%>
  </p>
<% end %>

<%= form_with model: @post, local:true do |f| %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field(:title, class: 'form-control', placeholder: 'Post Name')%>
  </div>
  <div class='form-group'>
    <%= f.label :body %>
    <%= f.text_area(:body, class: 'form-control', cols: 50, rows: 5, placeholder: 'Provide Description')%>
  </div>
  <% if @post.new_record? %>
    <%= f.submit("Create Post", class: 'btn btn-primary') %>
  <% else %>
    <%= f.submit("Update Post", class: 'btn btn-primary') %>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<div class='shadow-sm p-3 mb-5 bg-white rounded'>
  <h1 class='m-0'>
    <small class='text-muted'>
      Editing: 
    </small>
    <span class='badge badge-pill badge-info'>
      <%= @post.id %>
    </span>
    <%= @post.title %>
  </h1>
</div>
<div class='shadow p-3 mb-5 bg-white rounded'>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class='row'>
  <div class='col-2'>
  </div>

  <div class='col-10'>
    <div class='list-group'>
      <% @posts.each do |post| %>
        <%= link_to post do %>
          <li class='list-group-item'>
            <p><span class='badge badge-light'><%= post.id %></span> <%= post.title %></p>
            <small>Last Updated: <%= time_ago_in_words post.updated_at %></small>
          </li>
        <% end %>
      <% end %>
    </div>
  </div>
</div> 

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
  <div class='clearfix'>
    <h1 class='float-left'>
      <span class='badge badge-pill badge-info'>
        <%= @post.id %>
      </span>
      <%= @post.title %>
    </h1>
  </div>
  
  <hr/>
  <p class='shadow-none p-3 rounded'><%= @post.body %></p>
  <div>
    <% if can?(:crud,@post)%>
    <%= link_to "Edit", edit_post_path(@post), class: 'btn btn-info'%>
    <%= link_to(
      "Delete",
      post_path(@post),
      method: :delete,
      class: 'btn btn-danger',
      data: { confirm: 'are you sure?' },
      )
    %>
    </div>
    <% end %>
    
    <%= form_with model: [@post, @comment], local: true do |f| %>
    
    <div class='form-group'>
      
      <%= f.label :comment %>
      <%= f.text_area(:body, class: 'form-control', placeholder: 'Your thoughts here' )%>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>
<ul class = "List-group answer-List">
  <% @comments.each do |comment| %>
    <li class= "list-group-item">
      <%= comment.body %>
      <p>
     
      Commented <%= time_ago_in_words(comment.created_at)%>
       
        <% if can? :crud,comment %>
      <%= link_to(
        "Delete",
        post_comment_path(@post, comment),
        method: :delete,
        data: {
          confirm: "are you sure you want to delete this delete?"
        },
        class: "btn btn-danger btn-sm"
      )%>
      
      <% end %>
      
      </p>
    </li>
    <% end %>
</ul>

app/views/users/edit.html.erb
<%= form_with model: @user, method: :patch, local: true do |f| %>
  <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
  </div>
  <%= f.submit "Update User" , class: 'btn btn-success nav-item'%>
<% end %> 

<%= link_to 'Change Password', edit_password_path(@user), class: 'btn btn-success nav-item' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <div class= "form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name,class: 'form-control' %>
  </div>
  <div class= "form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name,class: 'form-control' %>
  </div>
  <div class= "form-group">
    <%= f.label :email %>
    <%= f.email_field :email,class: 'form-control' %>
  </div>
  <div class= "form-group">
    <%= f.label :password %>
    <%= f.password_field :password,class: 'form-control' %>
  </div>
  <div class= "form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation ,class: 'form-control'%>
  </div>
  <%= f.submit %>
<% end %>

app/views/users/password_edit.html.erb
<%= form_with model: @user, url: update_password_path, method: :patch, local: true do |f| %>
  <div class="form-group">
      <%= f.label :current_password %>
      <%= f.password_field :current_password, class: "form-control" %>
  </div>
  <div class="form-group">
      <%= f.label :new_password %>
      <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
      <%= f.label :new_password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <%= f.submit "Update User" , class: 'btn btn-success nav-item'%>
<% end %>